# Generated by Django 4.0.3 on 2022-05-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_table_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='group',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
