# Generated by Django 4.0.3 on 2022-05-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_class_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classname',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
