# Generated by Django 4.0.4 on 2022-05-03 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='problemid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.problem'),
            preserve_default=False,
        ),
    ]
