# Generated by Django 4.0.4 on 2022-05-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_submit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table_school',
            table='table_school',
        ),
    ]
