# Generated by Django 4.0.4 on 2022-05-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_table_school_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='restorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tel', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'restorant',
            },
        ),
    ]
