# Generated by Django 4.0.4 on 2022-05-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_parcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
