# Generated by Django 4.0.4 on 2022-05-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='nan',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
